version: '2'
plugins:
  fixme:
    enabled: true
  git-legal:
    enabled: true
    config:
      allow_affero_copyleft: true
      allow_strong_copyleft: true
  markdownlint:
    enabled: true
    checks:
      MD033:
        enabled: false # Disables inline html for use in projects
      MD002:
        enabled: false # Disables h1 missing check cause projects
  shellcheck:
    enabled: true
exclude_patterns:
  - '.github'
  - '.tmp'
