version: "2"
plugins:
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  editorconfig:
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: true
  git-legal:
    enabled: true
    config:
      allow_affero_copyleft: true
      allow_strong_copyleft: true
  markdownlint:
    enabled: true
    checks:
      MD033:
        enabled: false # Disables inline html for use in projects
      MD002:
        enabled: false # Disables h1 missing check cause projects
  reek:
    enabled: true
  rubocop:
    enabled: true
  sass-lint:
    enabled: true
    checks:
      mixins-before-declarations:
        enabled: false
  shellcheck:
    enabled: true
exclude_patterns:
  - ".github"
  - ".tmp"
