version: '2'

# Only the customized checks
checks:
  method-lines:
    config:
      # This is a lot bigger than default because it includes functional components in typescript
      threshold: 80
  method-complexity:
    config:
      # Triples the complexity since 5 is rather low as a default
      threshold: 12
