linters:
  LeadingZero:
    enabled: true
    style: exclude_zero # or 'include_zero'
  StringQuotes:
    enabled: true
    style: single_quotes # or double_quotes
  PropertySpelling:
    extra_properties:
      - grid-column-gap
      - grid-row-gap
      - grid-gap
      - grid-template-columns
      - grid-template-rows
      - grid-column-start
      - grid-row-start
      - grid-column-end
      - grid-row-end
  PropertyUnits:
    enabled: true
    properties:
      grid-template-columns: ['fr']