---
linters:
  rubocop:
    fixer: true
  shellcheck:
    shell: bash
  yamllint:
    config: ./yamllint.conf
files:
  ignore:
    - 'bower_components/*'
    - 'node_modules/*'
fixers:
  enable: true
