packageExtensions:
  '@prisma/client@*':
    dependencies:
      undici: ^4.9.3
  '@graphql-codegen/cli@*':
    dependencies:
      '@types/node': '*'
      'ts-node': '*'
      'typescript': '*'
  'graphql-config@*':
    dependencies:
      '@types/node': '*'
      'typescript': '*'
  'esbuild-runner@*':
    dependencies:
      esbuild: '*'
  '@sentry/nextjs@*':
    dependencies:
      '@babel/preset-env': '*'
      '@babel/core': '*'
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

yarnPath: .yarn/releases/yarn-3.2.0.cjs
