plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.1.1.cjs
packageExtensions:
  'eslint-plugin-tsc@*':
    dependencies:
      tsc: '^2.0.4'
      tslib: '^2.3.0'
  '@commitlint/load@*':
    dependencies:
      '@types/node': '*'
  '@endemolshinegroup/cosmiconfig-typescript-loader@*':
    dependencies:
      typescript: '^4.5.4'
  'relay-compiler@*':
    dependencies:
      graphql: '^15.0.0'
  'eslint-config-airbnb-typescript@*':
    dependencies:
      eslint: '^8.7.0'
      'eslint-plugin-import': '^2.25.4'
