packageExtensions:
  '@commitlint/load@*':
    dependencies:
      '@types/node': '*'
  '@endemolshinegroup/cosmiconfig-typescript-loader@*':
    dependencies:
      typescript: ^4.5.4
  '@prisma/client@*':
    dependencies:
      undici: ^4.9.3
  eslint-config-airbnb-typescript@*:
    dependencies:
      eslint: ^8.7.0
      eslint-plugin-import: ^2.25.4
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: ^0.3.4
  eslint-plugin-tsc@*:
    dependencies:
      tsc: ^2.0.4
      tslib: ^2.3.0
  relay-compiler@*:
    dependencies:
      graphql: ^15.0.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

yarnPath: .yarn/releases/yarn-3.1.1.cjs
