#! /bin/bash
set -e

# Executes some image minification scripts, then uses jekyll with the passed args
./optimize
JEKYLL_ENV=production bundle exec jekyll build
echo $(tput setaf 2)Your site is built successfully!$(tput sgr0)
