FROM node:15-slim

# Gotta be global so we can run yarn commands that reference it
RUN yarn global add gatsby-cli

# Set up perms correctly, as we aren't copying whole folder
WORKDIR /home/node/app
RUN chown -R node /home/node/app/

# Copy dependencies, install using yarn 2, and then copy rest
COPY package.json yarn.lock /home/node/app/
RUN yarn set version berry && yarn install
COPY gatsby-config.js /home/node/app/
COPY src /home/node/app/src

# Fixes permissions from the yarn install
RUN chown -R node /home/node/app/