FROM node:15.8

RUN apk add --no-cache --virtual .gyp python make g++

RUN yarn global add gatsby-cli

EXPOSE 8000

WORKDIR /home/node/app
ENV PATH /home/node/app/node_modules/.bin:$PATH

COPY package.json yarn.lock /home/node/app
RUN yarn install && yarn cache clean

CMD ["yarn", "serve"]