#! /bin/bash
set -e
ASSETS=./dg/_assets/img

# Echo an error message before exiting
err_report() {
    echo "$(tput setaf 1)optimize: error on line $1$(tput sgr0)"
}
trap 'err_report $LINENO' ERR

# First arg is filename extension of the original file
convert_files() {
echo "$(tput setaf 6)Beginning conversion of ${1}s...$(tput sgr0)"
for file in ${ASSETS}/*.$1; do
    fbname=$(basename "$file" .$1)
    output_file="${ASSETS}/${fbname}.webp"
    convert "${file}" ${output_file}
    echo "Created ${output_file}"
done
}

# Executes some image minification scripts
echo "$(tput setaf 6)Optimizing images...$(tput sgr0)"
#TODO: @dgattey fix imageoptim dg/_assets/img/
convert_files jpg
convert_files png
echo "$(tput setaf 2)Done optimizing!$(tput sgr0)"
