packages:
  - .
  - packages/*
  - apps/*

catalog:
  '@contentful/rich-text-types': 17.2.5
  '@fortawesome/free-brands-svg-icons': 7.1.0
  '@mui/material': 7.3.7
  '@mui/system': 7.3.7
  '@mui/utils': 7.3.7
  '@testing-library/dom': 10.4.1
  '@testing-library/jest-dom': 6.9.1
  '@testing-library/react': 16.3.2
  '@testing-library/user-event': 14.6.1
  '@types/jest': 30.0.0
  '@types/node': 25.0.10
  '@types/react': 19.2.9
  babel-plugin-react-compiler: 1.0.0
  dotenv-mono: 1.5.1
  graphql: 16.12.0
  graphql-request: 7.4.0
  jest: 30.2.0
  jest-environment-jsdom: 30.2.0
  lucide-react: 0.563.0
  next: 16.1.4
  react: 19.2.3
  server-only: 0.0.1
  sharp: 0.34.5
  ts-node: 10.9.2
  typescript: 5.9.3
  valibot: 1.2.0
  wretch: 3.0.6

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@vercel/speed-insights'
  - esbuild
  - sharp
  - unrs-resolver
