#! /bin/bash
set -e

# Installs dependencies
echo "$(tput setaf 6)Installing dependencies...$(tput sgr0)"
if gem list -i "^bundler" > /dev/null; then
    echo "Bundler already installed; skipping"
else
    gem install bundler
fi
if convert --version > /dev/null; then
  echo "ImageMagick already installed; skipping"
else
  brew install imagemagick
fi
echo "$(tput setaf 2)Done setting up!$(tput sgr0)"

