#! /bin/bash
set -e

# Installs dependencies
echo "$(tput setaf 6)Installing dependencies...$(tput sgr0)"
if gem list -i "^bundler" > /dev/null; then
    echo "Bundler already installed; skipping"
else
    gem install bundler -v '< 2.0'
fi
if convert --version > /dev/null; then
  echo "ImageMagick already installed; skipping"
else
  brew install imagemagick
fi
if npm -g --parseable list purgecss > /dev/null; then
	echo "purgecss already installed; skipping"
else
	npm install -g purgecss
fi
echo "$(tput setaf 2)Done setting up!$(tput sgr0)"

