---
permalink: browserconfig.xml
---

<?xml version="1.0" encoding="utf-8"?>
<browserconfig>
    <msapplication>
        <tile>
            <TileColor>#{{ site.app_theme_color }}</TileColor>
        </tile>
    </msapplication>
</browserconfig>
