const chrome = {
  dot: 'chrome__dot',
  footer: 'chrome__footer',
  header: 'chrome__header',
  links: 'chrome__links',
  logo: 'chrome__logo',
  logoInner: 'chrome__logoInner',
  music: 'chrome__music',
  musicChevron: 'chrome__musicChevron',
  musicLink: 'chrome__musicLink',
  musicList: 'chrome__musicList',
  musicPanel: 'chrome__musicPanel',
  musicPanelInner: 'chrome__musicPanelInner',
  musicSummary: 'chrome__musicSummary',
  nav: 'chrome__nav',
  nowPlaying: 'chrome__nowPlaying',
  nowPlayingInner: 'chrome__nowPlayingInner',
  scheme: 'chrome__scheme',
  schemeOption: 'chrome__schemeOption',
  schemeTrack: 'chrome__schemeTrack',
  spacer: 'chrome__spacer',
  srOnly: 'chrome__srOnly',
  stripInner: 'chrome__stripInner',
  stripMeta: 'chrome__stripMeta',
} as const;

export default chrome;
