import type { CutOutShape } from './cutOutShapes';
import type { PaperTone } from './types';

export type CutOutColor = PaperTone | 'star';

export type CutOutPlacement = {
  color: CutOutColor;
  id: string;
  mirrored?: true;
  rotationDeg: number;
  shape: CutOutShape;
  sizePx: number;
  underprint?: {
    color: CutOutColor;
    offset: readonly [x: number, y: number];
  };
  visibility: 'all' | 'desktop' | 'dark-desktop';
  xPercent: number;
  yPercent: number;
  zIndex: 0 | 1 | 3;
};

export const CUT_OUT_PLACEMENTS = {
  coda: [
    {
      color: 'olive',
      id: 'coda-monstera',
      rotationDeg: 14,
      shape: 'monstera',
      sizePx: 460,
      visibility: 'all',
      xPercent: 4,
      yPercent: -20,
      zIndex: 0,
    },
    {
      color: 'viridian',
      id: 'coda-banana',
      rotationDeg: -30,
      shape: 'banana',
      sizePx: 380,
      visibility: 'desktop',
      xPercent: 30,
      yPercent: 8,
      zIndex: 0,
    },
    {
      color: 'vermilion',
      id: 'coda-bird',
      rotationDeg: -10,
      shape: 'birdpara',
      sizePx: 260,
      underprint: {
        color: 'ultramarine',
        offset: [6, 7],
      },
      visibility: 'all',
      xPercent: 44,
      yPercent: 34,
      zIndex: 1,
    },
    {
      color: 'ochre',
      id: 'coda-sun',
      rotationDeg: 0,
      shape: 'sun',
      sizePx: 180,
      visibility: 'desktop',
      xPercent: 18,
      yPercent: 44,
      zIndex: 0,
    },
    {
      color: 'star',
      id: 'coda-star-upper',
      rotationDeg: 8,
      shape: 'star5',
      sizePx: 46,
      visibility: 'desktop',
      xPercent: 58,
      yPercent: 8,
      zIndex: 3,
    },
    {
      color: 'rose',
      id: 'coda-heart',
      rotationDeg: -12,
      shape: 'heart',
      sizePx: 90,
      visibility: 'all',
      xPercent: 90,
      yPercent: 70,
      zIndex: 3,
    },
    {
      color: 'cream',
      id: 'coda-star-lower',
      rotationDeg: 16,
      shape: 'star5',
      sizePx: 40,
      visibility: 'dark-desktop',
      xPercent: 24,
      yPercent: 78,
      zIndex: 3,
    },
    {
      color: 'cream',
      id: 'coda-star-right',
      rotationDeg: -6,
      shape: 'star4',
      sizePx: 34,
      visibility: 'dark-desktop',
      xPercent: 78,
      yPercent: 22,
      zIndex: 3,
    },
    {
      color: 'leaf',
      id: 'coda-philo',
      rotationDeg: -18,
      shape: 'philo',
      sizePx: 250,
      visibility: 'desktop',
      xPercent: 4,
      yPercent: 64,
      zIndex: 1,
    },
  ],
  helloSheet: [
    {
      color: 'ultramarine',
      id: 'hello-seaweed-left',
      rotationDeg: -12,
      shape: 'seaweed',
      sizePx: 250,
      visibility: 'desktop',
      xPercent: -4,
      yPercent: 20,
      zIndex: 1,
    },
    {
      color: 'olive',
      id: 'hello-fern-left',
      rotationDeg: 22,
      shape: 'fern',
      sizePx: 330,
      visibility: 'all',
      xPercent: -7,
      yPercent: 42,
      zIndex: 1,
    },
    {
      color: 'rose',
      id: 'hello-seaweed-lower-left',
      rotationDeg: -8,
      shape: 'seaweed2',
      sizePx: 180,
      visibility: 'all',
      xPercent: -2,
      yPercent: 78,
      zIndex: 1,
    },
    {
      color: 'ochre',
      id: 'hello-pods',
      rotationDeg: -18,
      shape: 'pods',
      sizePx: 210,
      visibility: 'desktop',
      xPercent: 33,
      yPercent: 74,
      zIndex: 1,
    },
    {
      color: 'star',
      id: 'hello-star-upper',
      rotationDeg: 12,
      shape: 'star5',
      sizePx: 40,
      visibility: 'desktop',
      xPercent: 44,
      yPercent: 10,
      zIndex: 3,
    },
    {
      color: 'star',
      id: 'hello-star-middle',
      rotationDeg: -8,
      shape: 'star4',
      sizePx: 30,
      visibility: 'desktop',
      xPercent: 47,
      yPercent: 50,
      zIndex: 3,
    },
    {
      color: 'rose',
      id: 'hello-algae',
      rotationDeg: 16,
      shape: 'algae',
      sizePx: 210,
      visibility: 'desktop',
      xPercent: 39,
      yPercent: -5,
      zIndex: 1,
    },
    {
      color: 'cream',
      id: 'hello-moon',
      rotationDeg: 14,
      shape: 'moon',
      sizePx: 64,
      visibility: 'dark-desktop',
      xPercent: 46,
      yPercent: -2,
      zIndex: 3,
    },
    {
      color: 'ultramarine',
      id: 'hello-coral',
      rotationDeg: -10,
      shape: 'coral',
      sizePx: 170,
      visibility: 'desktop',
      xPercent: 49,
      yPercent: 47,
      zIndex: 1,
    },
    {
      color: 'ultramarine',
      id: 'hello-seaweed-lower-middle',
      rotationDeg: 14,
      shape: 'seaweed2',
      sizePx: 200,
      visibility: 'desktop',
      xPercent: 53,
      yPercent: 72,
      zIndex: 1,
    },
    {
      color: 'leaf',
      id: 'hello-fern-right',
      rotationDeg: -28,
      shape: 'fern',
      sizePx: 320,
      visibility: 'desktop',
      xPercent: 69,
      yPercent: 78,
      zIndex: 0,
    },
    {
      color: 'vermilion',
      id: 'hello-bird',
      rotationDeg: 8,
      shape: 'birdpara',
      sizePx: 300,
      underprint: {
        color: 'ultramarine',
        offset: [6, 7],
      },
      visibility: 'all',
      xPercent: 60,
      yPercent: 64,
      zIndex: 1,
    },
    {
      color: 'viridian',
      id: 'hello-banana',
      rotationDeg: -24,
      shape: 'banana',
      sizePx: 440,
      visibility: 'desktop',
      xPercent: 86,
      yPercent: 26,
      zIndex: 0,
    },
    {
      color: 'ochre',
      id: 'hello-star-right',
      rotationDeg: 10,
      shape: 'star4',
      sizePx: 44,
      visibility: 'desktop',
      xPercent: 92,
      yPercent: 40,
      zIndex: 3,
    },
  ],
  moreWork: [
    {
      color: 'viridian',
      id: 'more-monstera',
      rotationDeg: 150,
      shape: 'monstera',
      sizePx: 640,
      visibility: 'all',
      xPercent: 72,
      yPercent: -12,
      zIndex: 0,
    },
    {
      color: 'vermilion',
      id: 'more-gerbe',
      rotationDeg: 24,
      shape: 'gerbe',
      sizePx: 380,
      visibility: 'all',
      xPercent: 38,
      yPercent: -16,
      zIndex: 0,
    },
    {
      color: 'star',
      id: 'more-star-upper',
      rotationDeg: -12,
      shape: 'star5',
      sizePx: 44,
      visibility: 'desktop',
      xPercent: 48,
      yPercent: 4,
      zIndex: 3,
    },
    {
      color: 'ultramarine',
      id: 'more-pods',
      rotationDeg: 22,
      shape: 'pods',
      sizePx: 230,
      visibility: 'all',
      xPercent: 27,
      yPercent: 36,
      zIndex: 1,
    },
    {
      color: 'rose',
      id: 'more-trefoil',
      rotationDeg: -16,
      shape: 'trefoil',
      sizePx: 150,
      visibility: 'desktop',
      xPercent: 45,
      yPercent: 44,
      zIndex: 1,
    },
    {
      color: 'leaf',
      id: 'more-algae',
      rotationDeg: 10,
      shape: 'algae',
      sizePx: 200,
      visibility: 'desktop',
      xPercent: 36,
      yPercent: 52,
      zIndex: 1,
    },
    {
      color: 'leaf',
      id: 'more-banana',
      rotationDeg: 40,
      shape: 'banana',
      sizePx: 440,
      visibility: 'desktop',
      xPercent: 80,
      yPercent: 52,
      zIndex: 0,
    },
    {
      color: 'ultramarine',
      id: 'more-star-lower',
      rotationDeg: 10,
      shape: 'star4',
      sizePx: 40,
      visibility: 'all',
      xPercent: 6,
      yPercent: 92,
      zIndex: 3,
    },
    {
      color: 'cream',
      id: 'more-seaweed',
      rotationDeg: -10,
      shape: 'seaweed',
      sizePx: 240,
      visibility: 'desktop',
      xPercent: -3,
      yPercent: 40,
      zIndex: 1,
    },
    {
      color: 'viridian',
      id: 'more-philo',
      rotationDeg: -30,
      shape: 'philo',
      sizePx: 300,
      visibility: 'all',
      xPercent: -6,
      yPercent: 8,
      zIndex: 1,
    },
    {
      color: 'cream',
      id: 'more-star-middle',
      rotationDeg: 20,
      shape: 'star5',
      sizePx: 40,
      visibility: 'desktop',
      xPercent: 31,
      yPercent: 54,
      zIndex: 1,
    },
  ],
  portrait: [
    {
      color: 'viridian',
      id: 'portrait-monstera',
      rotationDeg: -34,
      shape: 'monstera',
      sizePx: 1020,
      visibility: 'all',
      xPercent: -70,
      yPercent: -62,
      zIndex: 0,
    },
    {
      color: 'olive',
      id: 'portrait-philo',
      rotationDeg: 28,
      shape: 'philo',
      sizePx: 380,
      visibility: 'desktop',
      xPercent: 58,
      yPercent: 62,
      zIndex: 0,
    },
  ],
  workSheet: [
    {
      color: 'cream',
      id: 'work-algae',
      rotationDeg: -8,
      shape: 'algae',
      sizePx: 330,
      visibility: 'all',
      xPercent: -4,
      yPercent: 2,
      zIndex: 1,
    },
    {
      color: 'cream',
      id: 'work-star-upper',
      rotationDeg: 14,
      shape: 'star5',
      sizePx: 54,
      visibility: 'all',
      xPercent: 21,
      yPercent: 3,
      zIndex: 1,
    },
    {
      color: 'cream',
      id: 'work-swallow-upper',
      rotationDeg: -6,
      shape: 'swallow',
      sizePx: 170,
      visibility: 'all',
      xPercent: 55,
      yPercent: -2,
      zIndex: 1,
    },
    {
      color: 'cream',
      id: 'work-star-right',
      rotationDeg: 0,
      shape: 'star4',
      sizePx: 44,
      visibility: 'desktop',
      xPercent: 81,
      yPercent: 5,
      zIndex: 1,
    },
    {
      color: 'cream',
      id: 'work-seaweed',
      rotationDeg: 10,
      shape: 'seaweed',
      sizePx: 300,
      visibility: 'all',
      xPercent: 90,
      yPercent: 26,
      zIndex: 1,
    },
    {
      color: 'cream',
      id: 'work-coral',
      rotationDeg: -12,
      shape: 'coral',
      sizePx: 250,
      visibility: 'all',
      xPercent: 27,
      yPercent: 50,
      zIndex: 1,
    },
    {
      color: 'cream',
      id: 'work-star-lower-left',
      rotationDeg: -20,
      shape: 'star5',
      sizePx: 40,
      visibility: 'all',
      xPercent: 3,
      yPercent: 84,
      zIndex: 1,
    },
    {
      color: 'cream',
      id: 'work-trefoil',
      rotationDeg: 24,
      shape: 'trefoil',
      sizePx: 140,
      visibility: 'desktop',
      xPercent: 4,
      yPercent: 50,
      zIndex: 1,
    },
    {
      color: 'cream',
      id: 'work-swallow-lower',
      mirrored: true,
      rotationDeg: 12,
      shape: 'swallow',
      sizePx: 130,
      visibility: 'desktop',
      xPercent: 74,
      yPercent: 84,
      zIndex: 1,
    },
    {
      color: 'cream',
      id: 'work-star-bottom',
      rotationDeg: 12,
      shape: 'star4',
      sizePx: 36,
      visibility: 'all',
      xPercent: 48,
      yPercent: 92,
      zIndex: 1,
    },
    {
      color: 'cream',
      id: 'work-star-middle',
      rotationDeg: 30,
      shape: 'star5',
      sizePx: 34,
      visibility: 'desktop',
      xPercent: 66,
      yPercent: 40,
      zIndex: 1,
    },
    {
      color: 'cream',
      id: 'work-seaweed2',
      rotationDeg: -14,
      shape: 'seaweed2',
      sizePx: 220,
      visibility: 'desktop',
      xPercent: 88,
      yPercent: 70,
      zIndex: 1,
    },
  ],
} satisfies Record<
  'helloSheet' | 'portrait' | 'workSheet' | 'moreWork' | 'coda',
  ReadonlyArray<CutOutPlacement>
>;

const MORE_WORK_OVERFLOW_SOURCE_IDS = new Set<string>([
  'more-banana',
  'more-pods',
  'more-star-upper',
  'more-star-lower',
]);

export function moreWorkOverflowPlacements(unitKey: string): Array<CutOutPlacement> {
  return CUT_OUT_PLACEMENTS.moreWork
    .filter((placement) => MORE_WORK_OVERFLOW_SOURCE_IDS.has(placement.id))
    .map((placement) => ({
      ...placement,
      id: `${unitKey}-${placement.id}`,
    }));
}

export const ALL_CUT_OUT_PLACEMENTS: ReadonlyArray<CutOutPlacement> = [
  ...CUT_OUT_PLACEMENTS.helloSheet,
  ...CUT_OUT_PLACEMENTS.portrait,
  ...CUT_OUT_PLACEMENTS.workSheet,
  ...CUT_OUT_PLACEMENTS.moreWork,
  ...CUT_OUT_PLACEMENTS.coda,
];
