# Autochecks the repo, using formatting and linting commands we run on precommit JUUUUST to be sure
name: Autochecks
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  autocheck:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Each of these are yarn commands we should run and check output
        command: ['lint', 'lint:styles', 'lint:types', 'format']

    outputs:
      lint: ${{ steps.changes.outputs.lint }}
      lintstyles: ${{ steps.changes.outputs.lintstyles }}
      linttypes: ${{ steps.changes.outputs.linttypes }}
      format: ${{ steps.changes.outputs.format }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: yarn install
        # Make sure types are generated before running the commmand
      - run: yarn db:generate
      - name: ${{ matrix.command }}
        run: yarn ${{ matrix.command }}
      - name: Output changed files
        id: changes
        run: |
          CHANGED="$(git diff --name-only --diff-filter=ACMRT | xargs | sed s/package.json//g | sed s/yarn.lock//g)"
          COMMAND_NAME="${{ matrix.command }}"
          OUTPUTNAME="${COMMAND_NAME//:/}"
          echo "Changed files were: $CHANGED"
          echo "::set-output name=$OUTPUTNAME::$CHANGED"

  # If anything is output, fails this job!
  fail-on-diff:
    runs-on: ubuntu-latest
    needs: autocheck
    if: ${{ needs.autocheck.outputs.lint || needs.autocheck.outputs.lintstyles || needs.autocheck.outputs.linttypes || needs.autocheck.outputs.format }}
    steps:
      - name: Exiting because of changed files
        run: |
          echo "Changed from lint: ${{needs.autocheck.outputs.lint || 'none'}}"
          echo "Changed from style lint: ${{needs.autocheck.outputs.lintstyles || 'none'}}"
          echo "Type check changed files: ${{needs.autocheck.outputs.linttypes || 'none'}}"
          echo "Files formatted: ${{needs.autocheck.outputs.format || 'none'}}"
          exit 1
