# Autochecks the repo, using formatting and linting commands we run on precommit JUUUUST to be sure
name: Autochecks
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  autocheck:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Each of these are yarn commands we should run and check output
        command: ['lint', 'lint-styles', 'type-check', 'format']

    outputs:
      lint: ${{ steps.changes.outputs.lint }}
      lint-styles: ${{ steps.changes.outputs.lint-styles }}
      type-check: ${{ steps.changes.outputs.type-check }}
      format: ${{ steps.changes.outputs.format }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: yarn install
      - name: ${{ matrix.command }}
        run: yarn ${{ matrix.command }}
      - name: Output changed files
        id: changes
        run: |
          echo "Changed files were: $(git diff --name-only --diff-filter=ACMRT | xargs)"
          echo "::set-output name=${{ matrix.command }}::$(git diff --name-only --diff-filter=ACMRT | xargs)"

  # If anything is output, fails this job!
  fail-on-diff:
    runs-on: ubuntu-latest
    needs: autocheck
    if: ${{ needs.autocheck.outputs.lint || needs.autocheck.outputs.lint-styles || needs.autocheck.outputs.type-check || needs.autocheck.outputs.format }}
    steps:
      - name: Exiting because of changed files
        run: |
          echo "Changed from lint: ${{needs.autocheck.outputs.lint || 'none'}}"
          echo "Changed from lint-styles: ${{needs.autocheck.outputs.lint-styles || 'none'}}"
          echo "Type-check changed files: ${{needs.autocheck.outputs.type-check || 'none'}}"
          echo "Files formatted: ${{needs.autocheck.outputs.format || 'none'}}"
          exit 1
